name: Run Tests

on:
  pull_request:
  push:
    branches:
      - master
jobs:
  tests:
    timeout-minutes: 30
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ruby: ['2.6', '2.7']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-pr-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-pr-
      - name: Setup
        run: |
          gem install bundler
          bundle install
      - name: Test
        run: |
          bundle exec rake spec
